# Generated by Django 5.2 on 2025-05-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsWebb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
